USE [IG_Design]
GO
/****** Object:  Table [dbo].[Block]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Block](
	[BlockRecord] [char](10) NOT NULL,
	[UserID] [int] NOT NULL,
	[BlockUserID] [int] NOT NULL,
	[BlockTime] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Follower]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Follower](
	[followID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[FollowTime] [datetime] NOT NULL,
	[Agree] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Follower] PRIMARY KEY CLUSTERED 
(
	[followID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Likes]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Likes](
	[Likes] [int] NOT NULL,
	[type] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Likes] PRIMARY KEY CLUSTERED 
(
	[Likes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Media]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Media](
	[MediaID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[PostID] [int] NOT NULL,
	[MediaType] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Media] PRIMARY KEY CLUSTERED 
(
	[MediaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[Message] [nchar](10) NOT NULL,
	[UserID] [int] NOT NULL,
	[postMessage] [nvarchar](50) NOT NULL,
	[MessageTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[Message] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post](
	[PostID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[PostType] [nchar](10) NOT NULL,
	[Updatetime] [datetime] NULL,
	[PostPicture] [varbinary](50) NULL,
 CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED 
(
	[PostID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reply]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reply](
	[ReplyID] [int] NOT NULL,
	[CommentID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[ReplayContent] [nvarchar](50) NOT NULL,
	[Replytime] [datetime] NOT NULL,
 CONSTRAINT [PK_Reply] PRIMARY KEY CLUSTERED 
(
	[ReplyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Short]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Short](
	[ShortID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[ShortType] [nchar](10) NOT NULL,
	[PostText] [nchar](10) NOT NULL,
	[PostTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Short] PRIMARY KEY CLUSTERED 
(
	[ShortID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Story]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Story](
	[StoryID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[PostID] [int] NOT NULL,
	[UpdateTimes] [datetime] NOT NULL,
	[StoryType] [nchar](10) NOT NULL,
	[StoryContent] [nvarchar](50) NULL,
	[Likes] [int] NOT NULL,
 CONSTRAINT [PK_Story] PRIMARY KEY CLUSTERED 
(
	[StoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserID]    Script Date: 2024/7/28 下午 09:45:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserID](
	[UserID] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Photo] [varbinary](50) NOT NULL,
	[Gender] [char](10) NOT NULL,
	[location] [varchar](50) NOT NULL,
	[privacySetting] [nchar](10) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Follow] [int] NOT NULL,
 CONSTRAINT [PK_UserID] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Block]  WITH CHECK ADD  CONSTRAINT [FK_Block_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Block] CHECK CONSTRAINT [FK_Block_UserID]
GO
ALTER TABLE [dbo].[Follower]  WITH CHECK ADD  CONSTRAINT [FK_Follower_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Follower] CHECK CONSTRAINT [FK_Follower_UserID]
GO
ALTER TABLE [dbo].[Follower]  WITH CHECK ADD  CONSTRAINT [FK_Follower_UserID1] FOREIGN KEY([followID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Follower] CHECK CONSTRAINT [FK_Follower_UserID1]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Reply] FOREIGN KEY([UserID])
REFERENCES [dbo].[Reply] ([ReplyID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Reply]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_UserID]
GO
ALTER TABLE [dbo].[Post]  WITH CHECK ADD  CONSTRAINT [FK_Post_Media] FOREIGN KEY([PostID])
REFERENCES [dbo].[Media] ([MediaID])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT [FK_Post_Media]
GO
ALTER TABLE [dbo].[Post]  WITH CHECK ADD  CONSTRAINT [FK_Post_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT [FK_Post_UserID]
GO
ALTER TABLE [dbo].[Post]  WITH CHECK ADD  CONSTRAINT [FK_Post_UserID1] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT [FK_Post_UserID1]
GO
ALTER TABLE [dbo].[Reply]  WITH CHECK ADD  CONSTRAINT [FK_Reply_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Reply] CHECK CONSTRAINT [FK_Reply_UserID]
GO
ALTER TABLE [dbo].[Short]  WITH CHECK ADD  CONSTRAINT [FK_Short_Post] FOREIGN KEY([ShortID])
REFERENCES [dbo].[Post] ([PostID])
GO
ALTER TABLE [dbo].[Short] CHECK CONSTRAINT [FK_Short_Post]
GO
ALTER TABLE [dbo].[Short]  WITH CHECK ADD  CONSTRAINT [FK_Short_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Short] CHECK CONSTRAINT [FK_Short_UserID]
GO
ALTER TABLE [dbo].[Story]  WITH CHECK ADD  CONSTRAINT [FK_Story_Likes] FOREIGN KEY([Likes])
REFERENCES [dbo].[Likes] ([Likes])
GO
ALTER TABLE [dbo].[Story] CHECK CONSTRAINT [FK_Story_Likes]
GO
ALTER TABLE [dbo].[Story]  WITH CHECK ADD  CONSTRAINT [FK_Story_Post] FOREIGN KEY([StoryID])
REFERENCES [dbo].[Post] ([PostID])
GO
ALTER TABLE [dbo].[Story] CHECK CONSTRAINT [FK_Story_Post]
GO
ALTER TABLE [dbo].[Story]  WITH CHECK ADD  CONSTRAINT [FK_Story_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[UserID] ([UserID])
GO
ALTER TABLE [dbo].[Story] CHECK CONSTRAINT [FK_Story_UserID]
GO
